//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.02 at 01:00:17 AM EEST 
//


package com.geomark.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.geomark.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.geomark.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMostPopularPointsRequest }
     * 
     */
    public GetMostPopularPointsRequest createGetMostPopularPointsRequest() {
        return new GetMostPopularPointsRequest();
    }

    /**
     * Create an instance of {@link GetClosestPointsResponse }
     * 
     */
    public GetClosestPointsResponse createGetClosestPointsResponse() {
        return new GetClosestPointsResponse();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link GetMostPopularPointsResponse }
     * 
     */
    public GetMostPopularPointsResponse createGetMostPopularPointsResponse() {
        return new GetMostPopularPointsResponse();
    }

    /**
     * Create an instance of {@link GetClosestPointsRequest }
     * 
     */
    public GetClosestPointsRequest createGetClosestPointsRequest() {
        return new GetClosestPointsRequest();
    }

}
